# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 963ee43c6b4aa835cb234f0d94bad75c1bc60f5c96cbd6e5cbdbcac83d7d4ecec6297ad1cd4af9f19f73739d97625c794d1dcd1900a204ce29ac5ce017e85142

test:
  secret_key_base: a12c743c45bd07ff4dfccdb48c79c7b608af940c654934c4c19d98f83e69657b82c46bdbbcea0672a09bdac2d570e6dfce06fc21fd94b33549139858bcd7b38b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
